-- Storage access policies for the documents bucket.
--
-- Generated by scripts/storage-policies.mjs from the storage migration and the
-- driver one, replayed in that order. Edit the migrations, not this file.
--
-- Needed only when `supabase db push` warned that it could not apply them,
-- which happens when the role running migrations does not own storage.objects.
-- Paste this into the Supabase SQL Editor and run it once. Run it again after
-- the driver update: until you do, a driver cannot attach a delivery photo and
-- every member of the business can still read every file in the bucket.

drop policy if exists documents_read on storage.objects;
create policy documents_read on storage.objects
  for select to authenticated
  using (
    bucket_id = 'documents'
    and (storage.foldername(name))[1] = public.current_business_id()::text
  );

drop policy if exists documents_upload on storage.objects;
create policy documents_upload on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'documents'
    and (storage.foldername(name))[1] = public.current_business_id()::text
    and public.current_user_role() in ('owner', 'helper')
  );

drop policy if exists documents_update on storage.objects;
create policy documents_update on storage.objects
  for update to authenticated
  using (
    bucket_id = 'documents'
    and (storage.foldername(name))[1] = public.current_business_id()::text
    and public.current_user_role() in ('owner', 'helper')
  );

drop policy if exists documents_delete on storage.objects;
create policy documents_delete on storage.objects
  for delete to authenticated
  using (
    bucket_id = 'documents'
    and (storage.foldername(name))[1] = public.current_business_id()::text
    and public.current_user_role() = 'owner'
  );

drop policy if exists documents_read on storage.objects;
create policy documents_read on storage.objects
  for select to authenticated
  using (
    bucket_id = 'documents'
    and (storage.foldername(name))[1] = public.current_business_id()::text
    and (
      public.current_user_role() in ('owner', 'helper', 'ca')
      or public.driver_may_touch_object(name)
    )
  );

drop policy if exists documents_upload on storage.objects;
create policy documents_upload on storage.objects
  for insert to authenticated
  with check (
    bucket_id = 'documents'
    and (storage.foldername(name))[1] = public.current_business_id()::text
    and (
      public.current_user_role() in ('owner', 'helper')
      or public.driver_may_touch_object(name)
    )
  );
